# Generated by Django 2.2.11 on 2020-07-15 03:16

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import pharmacie.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('contact1', phonenumber_field.modelfields.PhoneNumberField(help_text='+22545485648', max_length=128, region=None)),
                ('contact2', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='+22545485648', max_length=128, region=None)),
                ('adresse', models.CharField(max_length=255)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('contact1', phonenumber_field.modelfields.PhoneNumberField(help_text='+22545485648', max_length=128, region=None)),
                ('contact2', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='+22545485648', max_length=128, region=None)),
                ('adresse', models.CharField(max_length=255)),
                ('embauche_le', models.DateField()),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('num_licence', models.CharField(max_length=255)),
                ('pays', django_countries.fields.CountryField(max_length=2)),
                ('adresse', models.CharField(max_length=255)),
                ('contact1', phonenumber_field.modelfields.PhoneNumberField(help_text='+22545485648', max_length=128, region=None)),
                ('contact2', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='+22545485648', max_length=128, region=None)),
                ('faxe', models.CharField(blank=True, max_length=50, verbose_name='FAXE')),
                ('email', models.EmailField(blank=True, max_length=120, verbose_name='ADRESSE EMAIL')),
                ('siteweb', models.CharField(blank=True, max_length=120, verbose_name='SITE WEB')),
                ('logo', models.ImageField(blank=True, upload_to=pharmacie.models.upload_logo, verbose_name='Logo')),
                ('description', models.TextField()),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c_gst', models.CharField(max_length=255)),
                ('s_gst', models.CharField(max_length=255)),
                ('num_lot', models.IntegerField(default=0)),
                ('num_produit', models.IntegerField(default=0)),
                ('date_production', models.DateField()),
                ('date_expiration', models.DateField()),
                ('description', models.TextField()),
                ('total_stock', models.IntegerField(default=0)),
                ('qte_stock', models.IntegerField(default=0)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('fournisseur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='SalaireEmp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salaire_date', models.DateField()),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='RequeteClt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Client')),
            ],
        ),
        migrations.CreateModel(
            name='DetailProd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salt_name', models.CharField(max_length=255)),
                ('salt_qte_type', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('produit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='DetailFacture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qte', models.IntegerField(default=0)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('facture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='CompteFournisseur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('1', 'Credit'), ('2', 'Debit')], max_length=15)),
                ('montant_transaction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_transaction', models.DateField()),
                ('mode_payement', models.CharField(max_length=255)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('fournisseur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='BanqueFrs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_compte_bancaire', models.CharField(max_length=255)),
                ('ifsc_num', models.CharField(max_length=255)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('fournisseur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='BanqueEmp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_compte_bancaire', models.CharField(max_length=255)),
                ('ifsc_num', models.CharField(max_length=255)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('emplyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Employer')),
            ],
        ),
    ]
